// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ7kJlMb7VQU8bvxzlJ9LnMMAkhbDUWrI',
    appId: '1:157300508610:web:b17d2feb76eb200d5f785b',
    messagingSenderId: '157300508610',
    projectId: 'simple-29484',
    authDomain: 'simple-29484.firebaseapp.com',
    storageBucket: 'simple-29484.appspot.com',
    measurementId: 'G-KSF03SN1SE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5AbviSp5oGaznuXNXksecJi4N0cU2w6E',
    appId: '1:157300508610:android:ab73148e51ed3cd05f785b',
    messagingSenderId: '157300508610',
    projectId: 'simple-29484',
    storageBucket: 'simple-29484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw1RlQ1XiFpjWhhEhHOUzLGVX0mh413zs',
    appId: '1:157300508610:ios:79bffd3ac7d163e85f785b',
    messagingSenderId: '157300508610',
    projectId: 'simple-29484',
    storageBucket: 'simple-29484.appspot.com',
    iosBundleId: 'com.example.simpleShoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw1RlQ1XiFpjWhhEhHOUzLGVX0mh413zs',
    appId: '1:157300508610:ios:79bffd3ac7d163e85f785b',
    messagingSenderId: '157300508610',
    projectId: 'simple-29484',
    storageBucket: 'simple-29484.appspot.com',
    iosBundleId: 'com.example.simpleShoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ7kJlMb7VQU8bvxzlJ9LnMMAkhbDUWrI',
    appId: '1:157300508610:web:683c3553c395c3885f785b',
    messagingSenderId: '157300508610',
    projectId: 'simple-29484',
    authDomain: 'simple-29484.firebaseapp.com',
    storageBucket: 'simple-29484.appspot.com',
    measurementId: 'G-4LME7GMBG3',
  );
}
